version: "3"

services:
  database:
    image: postgres:12
    container_name: "etl-database"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${DATABASE_EXTERNAL_PORT}:5432"
