"""empty message

Revision ID: 954855a617a9
Revises: 
Create Date: 2022-11-17 14:23:19.514450

"""
import sqlalchemy as sa
from alembic import op
from src.core import settings

# revision identifiers, used by Alembic.
revision = "954855a617a9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("rate_code", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("is_actual", sa.Boolean(), nullable=False),
        sa.Column("nominal", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=settings.DATABASE_SCHEMA,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("login", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_super_user", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=settings.DATABASE_SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users", schema="alexey")
    op.drop_table("rates", schema="alexey")
    # ### end Alembic commands ###
